function M = EllFit(beta,X,Y,Th) 

M = sum((-X+((beta(1)+beta(2).*cos(Th+beta(6)))*cos(beta(5))+...
        (beta(3)+beta(4).*sin(Th+beta(6)))*sin(beta(5)))).^2+...
        (-Y+(-(beta(1)+beta(2).*cos(Th+beta(6)))*sin(beta(5))+...
        (beta(3)+beta(4).*sin(Th+beta(6)))*cos(beta(5)))).^2);