function M = EllModel(beta,Th) 

T = Th(1:length(Th)/2);

M = [(beta(1)+beta(2).*cos(T+beta(6)))*cos(beta(5))+...
        (beta(3)+beta(4).*sin(T+beta(6)))*sin(beta(5)),... 
        -(beta(1)+beta(2).*cos(T+beta(6)))*sin(beta(5))+...
        (beta(3)+beta(4).*sin(T+beta(6)))*cos(beta(5))];
    