function exportData(app)

D = app.dataTable.Data;
DS = app.ExportdataButton.UserData;
DSc =  struct();
DSc.PSD_LWR = DS.PSD_LWR;
DSc.PSD_LWR_fit = DS.PSD_LWR_fit;
DSc.PSD_LWR_fit_unbiased = DS.PSD_LWR_fit_unbiased;

D = cell2table(D);

parameters = app.ExportdataButton.UserData.parameters;

VD = {'Selected'  'File Name'  'Type' 'Number of detected features' ...
    'CD' 'stdCD'   'LWR 3s' 'LWR' ...
    'LWR unbiased' 'LWR fit unbiased' ...
    'LWR 3s [nm]' 'LWR' ...
    'LWR unbiased' 'LWR fit unbiased' ...
    'LWR 3s [nm]' 'LWR' ...
    'LWR unbiased' 'LWR fit unbiased' ...
    'LW Corr. Length' 'LE Corr. Length' 'Leading LE Corr. Length' ...
    'Trailing LE Corr. Length'};
VN = {'Selected'  'File Name'  'Type' 'Number of detected features' ...
    'CD' 'stdCD'   'LWR_3s' 'LWR' ...
    'LWR_unbiased' 'LWR _fit_unbiased' ...
    'LWR_3s_[nm]' 'LWR' ...
    'LWR_unbiased' 'LWR_fit_unbiased' ...
    'LWR_3s_[nm]' 'LWR' ...
    'LWR_unbiased' 'LWR_fit_unbiased' ...
    'LW_Corr_Length' 'LE_Corr_Length' 'Leading_LE_Corr_Length' ...
    'Trailing_LE_Corr_Length'};


L = length(VN);
FN = fieldnames(parameters);
        cntp = 0;
        for kk = 1:length(FN)
            if (isnumeric(parameters.(FN{kk})) || islogical(parameters.(FN{kk}))) &&...
                    size(parameters.(FN{kk}),1)==1 && size(parameters.(FN{kk}),2)==1
                cntp = cntp+1;
                VD{L+cntp} = FN{kk};
                VN{L+cntp} = FN{kk};
            end
        end
D.Properties.VariableDescriptions = VD;
D.Properties.VariableNames = VN;

[filename, pathname] = uiputfile({'*.txt;*.xlsx;*.mat'});
if strcmpi(filename(end-2:end),'mat')
    save([pathname filename],'D','DSc')
else
    writetable(D,[pathname filename])
end