function [Fields, Fields_C] = FieldNames(app)

Fields = {...
'Selected', 'Selected data', 'Id';...
'FileName', 'File Name', 'File';...
'Type', 'Image Type', 'Type';...
'N_features', 'Number of detected features', 'N features';...
'AverageCD', 'Average CD', 'Average CD';...
'CDstd', 'CD standard deviation', 'CD std';...
'AverageLWR_3s','Average LWR 3sigma','Average LWR 3s';...
'AverageLWR_PSD','Average LWR PSD','Average LWR PSD';...
'AverageLWR_PSD_unbiased','Average LWR PSD unbiased','AverageLWR PSD unbiased';...
'AverageLWR_PSD_fit_unbiased','Average LWR PSD fit unbiased','AverageLWR PSDfit unbiased';...
'AverageLER_3s','Average LER 3s','Average LER 3s';...
'AverageLER_PSD','Average LER PSD','Average LER PSD';...
'AverageLER_PSD_unbiased','Average LER PSD unbiased','Average LER PSD unbiased';...
'AverageLER_PSD_fit_unbiased','Average LER PSD fit unbiased','Average LER PSDfit unbiased';...
'AverageLER_le_3s','AverageLER_le_3s','AverageLER_le_3s';...
'AverageLER_le_PSD','AverageLER_le_PSD','AverageLER_le_PSD';...
'AverageLER_le_PSD_unbiased','AverageLER_le_PSD_unbiased','AverageLER_le_PSD_unbiased';...
'AverageLER_le_PSD_fit_unbiased','AverageLER_le_PSD_fit_unbiased','AverageLER_le_PSD_fit_unbiased';...
'AverageLER_te_3s','AverageLER_te_3s','AverageLER_te_3s';...
'AverageLER_te_PSD','AverageLER_te_PSD','AverageLER_te_PSD';...
'AverageLER_te_PSD_unbiased','AverageLER_te_PSD_unbiased','AverageLER_te_PSD_unbiased';...
'AverageLER_te_PSD_fit_unbiased','AverageLER_te_PSD_fit_unbiased','AverageLER_te_PSD_fit_unbiased';...
% 'AlphaLWR','AlphaLWR','AlphaLWR';...
% 'AlphaLER','AlphaLER','AlphaLER';...
% 'AlphaLERle','AlphaLERle','AlphaLERle';...
% 'AlphaLERte','AlphaLERte','AlphaLERte';...
'Cl_LWR','Cl_LWR','Cl_LWR';...
'Cl_LER','Cl_LER','Cl_LER';...
'Cl_LERle','Cl_LERle','Cl_LERle';...
'Cl_LERte','Cl_LERte','Cl_LERte';...
'Spikes','Spikes','Spikes';...
'Bridges','Bridges','Bridges';...
'Pinches','Pinches','Pinches';...
'Undetected','Undetected','Undetected';...
'LPE_std','LPE_std','LPE_std';...
'LPE_p2v','LPE_p2v','LPE_p2v'};

Fields_C = {...
'Selected', 'Selected data', 'Id';...
'FileName', 'File Name', 'File';...
'Type', 'Image Type', 'Type';...
'N_features', 'Number of detected features', 'N features';...
'AverageDiameter', 'Average Diameter', 'Average Diameter';...
'Diameterstd', 'Diameter standard deviation', 'Diameter std';...
% 'AverageLWR_3s','Average LWR 3sigma','Average LWR 3s';...
% 'AverageLWR_PSD','Average LWR PSD','Average LWR PSD';...
% 'AverageLWR_PSD_unbiased','Average LWR PSD unbiased','AverageLWR PSD unbiased';...
% 'AverageLWR_PSD_fit_unbiased','Average LWR PSD fit unbiased','AverageLWR PSDfit unbiased';...
% 'AverageLER_3s','Average LER 3s','Average LER 3s';...
% 'AverageLER_PSD','Average LER PSD','Average LER PSD';...
% 'AverageLER_PSD_unbiased','Average LER PSD unbiased','Average LER PSD unbiased';...
% 'AverageLER_PSD_fit_unbiased','Average LER PSD fit unbiased','Average LER PSDfit unbiased';...
% 'AverageLER_le_3s','AverageLER_le_3s','AverageLER_le_3s';...
% 'AverageLER_le_PSD','AverageLER_le_PSD','AverageLER_le_PSD';...
% 'AverageLER_le_PSD_unbiased','AverageLER_le_PSD_unbiased','AverageLER_le_PSD_unbiased';...
% 'AverageLER_le_PSD_fit_unbiased','AverageLER_le_PSD_fit_unbiased','AverageLER_le_PSD_fit_unbiased';...
% 'AverageLER_te_3s','AverageLER_te_3s','AverageLER_te_3s';...
% 'AverageLER_te_PSD','AverageLER_te_PSD','AverageLER_te_PSD';...
% 'AverageLER_te_PSD_unbiased','AverageLER_te_PSD_unbiased','AverageLER_te_PSD_unbiased';...
% 'AverageLER_te_PSD_fit_unbiased','AverageLER_te_PSD_fit_unbiased','AverageLER_te_PSD_fit_unbiased';...
% % 'AlphaLWR','AlphaLWR','AlphaLWR';...
% % 'AlphaLER','AlphaLER','AlphaLER';...
% % 'AlphaLERle','AlphaLERle','AlphaLERle';...
% % 'AlphaLERte','AlphaLERte','AlphaLERte';...
% 'Cl_LWR','Cl_LWR','Cl_LWR';...
% 'Cl_LER','Cl_LER','Cl_LER';...
% 'Cl_LERle','Cl_LERle','Cl_LERle';...
% 'Cl_LERte','Cl_LERte','Cl_LERte';...
% 'Spikes','Spikes','Spikes';...
% 'Bridges','Bridges','Bridges';...
% 'Pinches','Pinches','Pinches';...
% 'Undetected','Undetected','Undetected';...
% 'LPE_std','LPE_std','LPE_std';...
% 'LPE_p2v','LPE_p2v','LPE_p2v';...
'AverageMajorAx','AverageMajorAx','AverageMajorAx';...
'MajorAxSTD','Major Axis STD','Major Ax STD';...
'AverageMinorAx','AverageMinorAx','AverageMinorAx';...
'MinorAxSTD','Minor Axis STD','Minor Ax STD';...
'AverageEllipticity','Average Ellipticity','Average Ellipticity';...
'EllipticitySTD','Ellipticity STD','Ellipticity  STD';...
'AverageMajorAA','Average major axis angle','Average major axis angle';...
'MajorAAstd','MajorAAstd','MajorAAstd';...
'GridXstd','Grid X std','GridX std';...
'GridYstd','Grid Y std','GridY std';...
'Hpitch','Horizontal pitch','H pitch';...
'Vpitch','Vertical pitch','V pitch'};

app.dataTable.ColumnName=Fields(:,2);        
app.dataTable_Contacts.ColumnName=Fields_C(:,2);        
app.dataTable.ColumnEditable = [true false(1,numel(app.dataTable.ColumnName)-1)];
app.dataTable_Contacts.ColumnEditable = [true false(1,numel(app.dataTable_Contacts.ColumnName)-1)];