load('~/Desktop/test.mat');

filename = 'MyTestExportFile.xlsx';

fnames = D.File_Name;
fnamesc = Dc.File_Name;

writecell(fnames(1:end-1,1),filename,'FileType','Spreadsheet',...
    'Sheet','Image List');
writecell(fnamesc,filename,'FileType','Spreadsheet',...
    'Sheet','Image List','WriteMode','append');

%Lines
if ~isempty(D)
    writetable(D,filename,'FileType','Spreadsheet',...
        'Sheet','Lines Data')
    A = Ddata.LeadingEdges;
    for n = 1:size(A,2)
        writematrix(A{1,n}*Ddata.PS(n),filename,'FileType','Spreadsheet',...
            'Sheet',['Image ' num2str(n) ' Leading edges' ]);
    end
    B = Ddata.TrailingEdges;
    for n = 1:size(B,2)
        writematrix(B{1,n}*Ddata.PS(n),filename,'FileType','Spreadsheet',...
            'Sheet',['Image ' num2str(n) ' Trailing edges' ]);
    end

    labels = {'Frequency','PSD LWR','PSD LWR fit','PSD LWR fit unbiased',...
        'PSD LER','PSD LER fit','PSD LER fit unbiased',...
        'PSD LERl','PSD LERl fit','PSD LERl fit unbiased',...
        'PSD LERt','PSD LERt fit','PSD LERt fit unbiased'};
    for n = 1:size(Ddata.Frequency,2)
        sheetName = ['Image ' num2str(n) ' PSD'];
        writecell(labels,filename,'FileType','spreadsheet',...
            'Sheet',sheetName)
        writematrix(Ddata.Frequency{n}',filename,'FileType','spreadsheet',...
            'Sheet',sheetName,'WriteMode','append')
        writematrix(Ddata.PSD_LWR{n},filename,'FileType','spreadsheet',...
            'Sheet',sheetName,'Range','B2')
        writematrix(Ddata.PSD_LWR_fit{n},filename,'FileType','spreadsheet',...
            'Sheet',sheetName,'Range','C2')
        writematrix(Ddata.PSD_LWR_fit_unbiased{n},filename,'FileType','spreadsheet',...
            'Sheet',sheetName,'Range','D2')
        writematrix(Ddata.PSD_LER{n},filename,'FileType','spreadsheet',...
            'Sheet',sheetName,'Range','E2')
        writematrix(Ddata.PSD_LER_fit{n},filename,'FileType','spreadsheet',...
            'Sheet',sheetName,'Range','F2')
        writematrix(Ddata.PSD_LWR_fit_unbiased{n},filename,'FileType','spreadsheet',...
            'Sheet',sheetName,'Range','G2')
        writematrix(Ddata.PSD_LERl{n},filename,'FileType','spreadsheet',...
            'Sheet',sheetName,'Range','H2')
        writematrix(Ddata.PSD_LERl_fit{n},filename,'FileType','spreadsheet',...
            'Sheet',sheetName,'Range','I2')
        writematrix(Ddata.PSD_LERl_fit_unbiased{n},filename,'FileType','spreadsheet',...
            'Sheet',sheetName,'Range','J2')
        writematrix(Ddata.PSD_LERt{n},filename,'FileType','spreadsheet',...
            'Sheet',sheetName,'Range','K2')
        writematrix(Ddata.PSD_LERt_fit{n},filename,'FileType','spreadsheet',...
            'Sheet',sheetName,'Range','L2')
        writematrix(Ddata.PSD_LERt_fit_unbiased{n},filename,'FileType','spreadsheet',...
            'Sheet',sheetName,'Range','M2')
        

    end



end


if ~isempty(Dc)
    writetable(Dc,filename,'FileType','Spreadsheet',...
        'Sheet','Contacts Data')
end